name: Trigger argo worflow
on:
    workflow_call:
      inputs:
        image_tag:
          required: true
          type: string

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          repository: KevPoirier/gitops
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gitops

      - name: Update deployment.yaml with new tag
        run: |
          FILE="gitops/microservices/base/deployment.yaml"
          sed -i "s|image: synerkevin/exogithubactions:.*|image: synerkevin/exogithubactions:${{ inputs.image_tag }}|" $FILE

      - name: Commit and push
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image tag to ${{ inputs.image_tag }}"
          git push