name: Trigger argo worflow
on:
    workflow_call:
      inputs:
        image_tag:
          required: true
          type: string
      secrets:
        gitops_pat:
          required: true

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gitops repo
        uses: actions/checkout@v4
      
      - name: Show kustomization.yaml before sed
        run: cat gitops/microservices/overlays/poker/kustomization.yaml
      
      - name: Update image tag in kustomization.yaml
        run: |
          FILE="gitops/microservices/overlays/poker/kustomization.yaml"
          sed -i "s|newTag: .*|newTag: ${{ inputs.image_tag }}|" $FILE

      - name: Show kustomization.yaml after sed
        run: cat gitops/microservices/overlays/poker/kustomization.yaml

      - name: Show git status
        run: |
          cd gitops
          git status

      - name: Debug token (temporaire)
        run: | 
          echo "Token present: ${{ secrets.gitops_pat != '' }}"
          echo "Token = ${{ secrets.gitops_pat }}"

      - name: Commit and push
        run: |
          cd gitops
          git config user.name "KevPoirier"
          git config user.email "kevin.poirier@synerglass-soft.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/KevPoirier/gitops.git
          git add .
          git commit -m "Update image tag to ${{ inputs.image_tag }}" || echo "No changes to commit"
          git remote -v  # debug: montre si l'URL avec token est bien utilisée
          git push