name: Trigger argo worflow
on:
    workflow_call:
      inputs:
        image_tag:
          required: true
          type: string

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          repository: KevPoirier/gitops
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gitops
      
      - name: Show deployment.yaml before sed
        run: cat gitops/microservices/base/deployment.yaml
      
      - name: Update image tag in kustomization.yaml
        run: |
          FILE="gitops/microservices/base/kustomization.yaml"
          sed -i "s|newTag: .*|newTag: ${{ inputs.image_tag }}|" $FILE

      - name: Show deployment.yaml after sed
        run: cat gitops/microservices/base/deployment.yaml

      - name: Commit and push
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image tag to ${{ inputs.image_tag }}"
          git push